server:
  port: 9090
  servlet:
    context-path: /offer
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin123@offer-manage.mmcf7.mongodb.net/?retryWrites=true&w=majority&appName=offer-manage
      database: offer-manage
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true